// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6baWo5LD8BeZ9xnnwJ6ZKOhze7rFFRBs',
    appId: '1:343165366695:web:45bd735ad7e9537b09c682',
    messagingSenderId: '343165366695',
    projectId: 'anmka-pathologybro-main',
    authDomain: 'anmka-pathologybro-main.firebaseapp.com',
    storageBucket: 'anmka-pathologybro-main.firebasestorage.app',
    measurementId: 'G-QXCZF2HSG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_J3GGNwBt0FHLO2MkvqR-1S0qz7bHgFI',
    appId: '1:343165366695:android:a8ee74d13a9a942709c682',
    messagingSenderId: '343165366695',
    projectId: 'anmka-pathologybro-main',
    storageBucket: 'anmka-pathologybro-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKpqOUOS0xG5LPKF4wjuAyhh2lAu3uyZQ',
    appId: '1:343165366695:ios:779b7274755b4be009c682',
    messagingSenderId: '343165366695',
    projectId: 'anmka-pathologybro-main',
    storageBucket: 'anmka-pathologybro-main.firebasestorage.app',
    iosBundleId: 'com.webinar.webinar',
  );
}
